kind: Secret
apiVersion: v1
metadata:
  annotations:
    controller.devfile.io/mount-as: env
  name: opencode-config
  namespace: openshift-devspaces
  labels:
    app.kubernetes.io/component: workspaces-config
    app.kubernetes.io/part-of: che.eclipse.org
    controller.devfile.io/mount-to-devworkspace: 'true'
    controller.devfile.io/watch-secret: 'true'
type: Opaque
stringData:
  NEXUS_PASSWORD: "not4RealPw!!"
  VLLM_API_KEY: "not4realAP1k3y!"
